version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:staging
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      - POSTGRES_HOST=identity-service-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=identityDB
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_JAAS_CONFIG=
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SMTP_HOST=maildev
      - SMTP_PORT=25
      - SMTP_DEFAULT_FROM=nimble@local-dev
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_AUTH=false
      - SMTP_STARTTLS=false

    ports:
      - "9096:9096"
    networks:
      - infra
      - identity-backend
    depends_on:
      - identity-service-db

  identity-service-db:
    image: postgres:9.6.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=identityDB
      - _JAVA_OPTIONS=-Xmx512m -Xms50m

    networks:
      - identity-backend

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:staging
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      - BUSINESS_PROCESS_DB_HOST=business-process-service-db
      - BUSINESS_PROCESS_DB_PORT=5432
      - BUSINESS_PROCESS_DB_NAME=businessprocessengine
      - BUSINESS_PROCESS_DB_USERNAME=postgres
      - BUSINESS_PROCESS_DB_PASSWORD=postgres
      - UBL_DB_HOST=ubl-db
      - UBL_DB_HOST_PORT=5432
      - UBL_DB_NAME=ubldb
      - UBL_DB_USERNAME=postgres
      - UBL_DB_PASSWORD=postgres
      - CAMUNDA_DB_HOST=camunda-db
      - CAMUNDA_DB_PORT=5432
      - CAMUNDA_DB_NAME=camunda
      - CAMUNDA_DB_USERNAME=postgres
      - CAMUNDA_DB_PASSWORD=postgres
      - BINARY_CONTENT_DB_HOST=binary-content-db
      - BINARY_CONTENT_DB_PORT=5432
      - BINARY_CONTENT_DB_NAME=binarycontentdb
      - BINARY_CONTENT_DB_USERNAME=postgres
      - BINARY_CONTENT_DB_PASSWORD=postgres
      - BINARY_CONTENT_URL=http://not-yet-in-use/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_JAAS_CONFIG=
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SMTP_HOST=maildev
      - SMTP_PORT=25
      - SMTP_DEFAULT_FROM=nimble@local-dev
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_AUTH=false
      - SMTP_STARTTLS=false
      
    mem_limit: 2000m
    ports:
      - "8085:8085"
    networks:
      - infra
      - business-process-backend
    depends_on:
      - business-process-service-db
      - camunda-db
      - ubl-db
      - catalog-service-srdc

  business-process-service-db:
    image: postgres:9.6.3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: businessprocessengine
    networks:
      - business-process-backend

  camunda-db:
    image: postgres:9.6.3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camunda
    networks:
      - business-process-backend

  ubl-db:
    image: postgres:9.6.3
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ubldb
    networks:
      - business-process-backend
      - catalog-backend

  binary-content-db:
    image: postgres:9.6.3
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: binarycontentdb
    networks:
      - business-process-backend
      - catalog-backend

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service-micro:5.0.1
    # image: nimbleplatform/catalogue-service:latest
    ports:
      - "10095:8095"
    env_file:
      - env_vars
      - env_vars-dev
    networks:
      - infra
      - catalog-backend
    environment:
      - UBL_DB_HOST=ubl-db
      - UBL_DB_HOST_PORT=5432
      - UBL_DB_NAME=ubldb
      - UBL_DB_USERNAME=postgres
      - UBL_DB_PASSWORD=postgres
      - CATEGORY_DB_HOST=category-db
      - CATEGORY_DB_PORT=5432
      - CATEGORY_DB_NAME=categorydb
      - CATEGORY_DB_USERNAME=postgres
      - CATEGORY_DB_PASSWORD=postgres
      - SYNC_DB_HOST=sync-db
      - SYNC_DB_PORT=5432
      - SYNC_DB_NAME=syncdb
      - SYNC_DB_USERNAME=postgres
      - SYNC_DB_PASSWORD=postgres
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_JAAS_CONFIG=
    depends_on:
      - category-db
      - ubl-db
      - sync-db
      - marmotta

  marmotta:
    image: nimbleplatform/marmotta:staging
    environment:
      - "database.user=postgres"
      - "database.password=postgres"
      - "database.url=jdbc:postgresql://marmotta-db:5432/marmotta?prepareThreshold=3"
      - "database.type=postgres"
      - "kiwi.path=/marmotta"
      - "kiwi.context=http://localhost:8082/"
      - "kiwi.host=http://localhost:8082"
    ports:
      - "8082:8080"
    depends_on:
      - marmotta-db
    networks: 
      - infra

  marmotta-db:
    build: ./marmotta-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marmotta
    ports:
      - "5437:5432"
    networks:
      - infra
    

  # EMPTY CATEGORY DB (eClass isn't public)
  category-db:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: categorydb
    networks:
      - infra

  sync-db:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: syncdb
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:staging
    environment:
      TARGET_ENVIRONMENT: dev
    ports:
      - "8081:8080" # external port: 8081
    env_file:
      - env_vars
      - env_vars-dev
    networks:
      - infra
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    networks:
      - infra


  ###############################
  ######## Trust Service ########
  ###############################

  trust-service:
    image: nimbleplatform/trust-service:staging
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      - PORT=9098
      - _JAVA_OPTIONS=-Xmx256m -Xms128m
      - TRUST_DB_HOST=trust-service-db
      - TRUST_DB_NAME=trustdb
      - TRUST_DB_USERNAME=postgres
      - TRUST_DB_PASSWORD=admin123
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_JAAS_CONFIG=
    mem_limit: 800m
    ports:
      - "9098:9098"
    depends_on:
      - trust-service-db
    networks:
      - infra

  trust-service-db:
    build: ./trust-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: trustdb
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfra_default
  identity-backend:
  catalog-backend:
  business-process-backend:
