version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:latest
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      - POSTGRES_HOST=identity-service-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=identityDB
    ports:
      - "9096:9096"
    networks:
      - infra
      - identity-backend
    depends_on:
      - identity-service-db

  identity-service-db:
    image: postgres:9.6.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=identityDB
      - _JAVA_OPTIONS=-Xmx768m -Xms50m

    networks:
      - identity-backend

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:latest
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      - BUSINESS_PROCESS_DB_HOST=business-process-service-db
      - BUSINESS_PROCESS_DB_PORT=5432
      - BUSINESS_PROCESS_DB_NAME=businessprocessengine
      - BUSINESS_PROCESS_DB_USERNAME=postgres
      - BUSINESS_PROCESS_DB_PASSWORD=postgres
      - CAMUNDA_DB_HOST=camunda-db
      - CAMUNDA_DB_PORT=5432
      - CAMUNDA_DB_NAME=camunda
      - CAMUNDA_DB_USERNAME=postgres
      - CAMUNDA_DB_PASSWORD=postgres
      - _JAVA_OPTIONS=-Xmx1536m -Xms50m
    ports:
      - "8085:8085"
    networks:
      - infra
      - business-process-backend
    depends_on:
      - business-process-service-db
      - camunda-db

  business-process-service-db:
    image: postgres:9.6.3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: businessprocessengine
    networks:
      - business-process-backend

  camunda-db:
    image: postgres:9.6.3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camunda
    networks:
      - business-process-backend

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    ##image: nimbleplatform/catalogue-service-micro:latest ???
    image: nimbleplatform/catalogue-service:latest
    ports:
      - "10095:8095"
    env_file:
      - env_vars
      - env_vars-dev
    networks:
      - infra
      - catalog-backend
    environment:
      - _JAVA_OPTIONS=-Xmx1536m -Xms50m

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:latest
    ports:
      - "8081:8080" # external port: 8081
    env_file:
      - env_vars
      - env_vars-dev
    networks:
      - infra
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-dev
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfra_default
  identity-backend:
  catalog-backend:
  business-process-backend: