version: '2'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    ports:
      - "8888:8888"

  service-discovery:
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  gateway-proxy:
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
    ports:
      - "443:80"
    depends_on:
      - config-server
      - service-discovery

  hystrix-dashboard:
    image: nimbleplatform/hystrix-dashboard:latest
    env_file:
      - env_vars
    ports:
      - "9080:9080"
    depends_on:
      - config-server
      - service-discovery

  ##########################
  ######## Keycloak ########
  ##########################

  keycloak:
    image: jboss/keycloak-postgres:3.2.0.Final
    env_file:
      - keycloak_default_env
      - keycloak_secrets
    links:
      - keycloak-db:postgres
    ports:
      - "10096:8080"
      - "9999:9990"
      - "8088:8443"
    volumes:
      - ./data:/data
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:9.6.3
    env_file:
      - keycloak_default_env
      - keycloak_secrets
