version: '2'

services:
  marmotta:
    image: nimbleplatform/marmotta:staging
    volumes:
       - marmotta-config:/var/lib/marmotta/
    environment:
      - "database.user=admin"
      - "database.url=jdbc:postgresql://marmotta-db:5432/marmottadb?prepareThreshold=3"
      - "database.type=postgres"
    env_file:
      - ./env
    ports:
      - "8086:8080"
    networks:
      - nimble-cloud-infra
    depends_on:
      - marmotta-db

  marmotta-db:
    image: postgres:9.6.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=marmottadb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  marmotta-config:
  pgdata:

networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfrastaging_default