version: '3'

services:

  ###################################################################
  ############################# KEYCLOAK ############################
  ###################################################################
  keycloak:
    image: jboss/keycloak:4.3.0.Final
    restart: on-failure
    ports:
    - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    command:
    - "-b"
    - "0.0.0.0"
    - "-Dkeycloak.migration.action=import"
    - "-Dkeycloak.migration.provider=dir"
    - "-Dkeycloak.migration.dir=/migration/"
    - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
    - ./migration/:/migration/
    - ./theme/:/opt/jboss/keycloak/themes/nimble-theme
    depends_on:
    - keycloak-db

  keycloak-db:
    image: postgres:10
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
    driver: local
