version: "3"

services:
  influxdb:
    image: nimbleplatform/influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - "nimble-cloud-infra"

  mosquitto:
    image: nimbleplatform/eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"
    links:
      - telegraf
    restart: always
    networks:
      - "nimble-cloud-infra"

  telegraf:
    image: nimbleplatform/telegraf:1.13
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - "nimble-cloud-infra"

  grafana:
    image: nimbleplatform/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    links:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - "nimble-cloud-infra"

volumes:
  influxdb:
  grafana:

networks:
  nimble-cloud-infra:
