services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    ports:
      - "8888:8888"
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    networks:
      - efactory-network

  service-discovery:
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    networks:
      - efactory-network

  gateway-proxy:
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
        #    ports:
      #      - "80:80"
    depends_on:
      - config-server
      - service-discovery
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    networks:
      - efactory-network
networks:
  efactory-network:
    external:
      name: security-network
