version: '2'

services:
  keycloak:
     image: jboss/keycloak:3.4.0.Final
     env_file:
       - keycloak_default_env
       - keycloak_secrets
     ports:
       - "10096:8080"
       - "9999:9990"
       - "8088:8443"
     networks:
       - nimble-cloud-infra

networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfraprod_default