version: '2'

services:
  keycloak:
     build: .
     env_file:
       - keycloak_default_env
       - keycloak_secrets
     ports:
       - "10097:8080"
       - "10098:9990"
       - "10099:8443"
     networks:
       - nimble-cloud-infra

networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfraprod_default